### ISSUE TITLE
ERROR NoMethodError: undefined method `key?' for nil:NilClass

### ISSUE THREAD

**Issue by fangzhouli** [academicpages/academicpages.github.io#1032]
Error Message:
```
[2022-09-25 18:15:24] ERROR NoMethodError: undefined method `key?' for nil:NilClass
        /var/lib/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve/servlet.rb:191:in `conditionally_inject_charset'
        /var/lib/gems/3.0.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve/servlet.rb:176:in `do_GET'
        /var/lib/gems/3.0.0/gems/hawkins-2.0.5/lib/hawkins/servlet.rb:134:in `do_GET'
        /usr/share/rubygems-integration/all/gems/webrick-1.7.0/lib/webrick/httpservlet/abstract.rb:105:in `service'
        /usr/share/rubygems-integration/all/gems/webrick-1.7.0/lib/webrick/httpservlet/filehandler.rb:242:in `service'
        /usr/share/rubygems-integration/all/gems/webrick-1.7.0/lib/webrick/httpserver.rb:140:in `service'
        /usr/share/rubygems-integration/all/gems/webrick-1.7.0/lib/webrick/httpserver.rb:96:in `run'
        /usr/share/rubygems-integration/all/gems/webrick-1.7.0/lib/webrick/server.rb:310:in `block in start_thread'`
```
Outcome:
- Page Not Found

**Comment by MKLOL** [comment]
jekyll-3.9.2 is broken for osx for w/e reason. Revert to 3.9.0.

I added this to my Gemfile. Though I'm new to ruby so there might be an easier way. 

```
gem "jekyll", "3.9.0"
gem "jekyll-paginate"
gem "jekyll-gist"
gem "jekyll-redirect-from"
gem "kramdown-parser-gfm"
gem "webrick"
```

**Comment by fangzhouli** [comment]
Thanks MKLOL. I will try it and update you the outcome!

**Comment by fangzhouli** [comment]
It worked, thank you sir!

**Comment by Jiayunvv** [comment]
Thanks MKLOL, it worked for me! Just as a supplementary note:
After I modified the Gemfile and ran 'bundle exec jekyll liveserve', I encountered the following problem:
'You requested Jekyll version 3.9.0, but the bundle currently has Jekyll locked at 3.9.3. '
To resolve this issue, just simply deleted the Gemfile.lock and it will be fine.
