### ISSUE TITLE
Error building / deploying site

### ISSUE THREAD

**Issue by krystalrain** [academicpages/academicpages.github.io#1065]
I just started using this template and after making my first edits in the about.md file I get the follow error

```
Run actions/jekyll-build-pages@v1
/usr/bin/docker run --name ghcrioactionsjekyllbuildpagesv104_660663 --label 8d5581 --workdir /github/workspace --rm -e "INPUT_SOURCE" -e "INPUT_DESTINATION" -e "INPUT_FUTURE" -e "INPUT_BUILD_REVISION" -e "INPUT_VERBOSE" -e "INPUT_TOKEN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/krystalrain.github.io/krystalrain.github.io":"/github/workspace" ghcr.io/actions/jekyll-build-pages:v1.0.4
/usr/local/bundle/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:143:in `parse': (/github/workspace/./_config.yml): found character that cannot start any token while scanning for the next token at line 60 column 37 (Psych::SyntaxError)
	from /usr/local/bundle/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:143:in `load'
  Logging at level: debug
	from /usr/local/bundle/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `block in load_file'
github-pages 227 | Error:  (/github/workspace/./_config.yml): found character that cannot start any token while scanning for the next token at line 60 column 37
	from /usr/local/bundle/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `open'
	from /usr/local/bundle/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `load_file'
	from /usr/local/bundle/gems/jekyll-3.[9](https://github.com/krystalrain/krystalrain.github.io/actions/runs/3293557466/jobs/5430182869#step:4:10).2/lib/jekyll/configuration.rb:143:in `safe_load_file'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/configuration.rb:180:in `read_config_file'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/configuration.rb:207:in `block in read_config_files'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/configuration.rb:205:in `each'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/configuration.rb:205:in `read_config_files'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll.rb:[11](https://github.com/krystalrain/krystalrain.github.io/actions/runs/3293557466/jobs/5430182869#step:4:12)3:in `configuration'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/command.rb:43:in `configuration_from_options'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:29:in `process'
	from /usr/local/bundle/gems/github-pages-227/bin/github-pages:70:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:[19](https://github.com/krystalrain/krystalrain.github.io/actions/runs/3293557466/jobs/5430182869#step:4:20):in `program'
	from /usr/local/bundle/gems/github-pages-[22](https://github.com/krystalrain/krystalrain.github.io/actions/runs/3293557466/jobs/5430182869#step:4:23)7/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:[23](https://github.com/krystalrain/krystalrain.github.io/actions/runs/3293557466/jobs/5430182869#step:4:24):in `load'
	from /usr/local/bundle/bin/github-pages:23:in `<main>'
```

**Comment by wvirany** [comment]
Hi, can you share what you did to fix this error?
