### ISSUE TITLE
jekyll 3.9.3 | Error:  undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by Matheart** [academicpages/academicpages.github.io#2267]
The following error message is displayed in the github action while building the page
```
Run bundle exec jekyll build --baseurl ""
  
jekyll 3.9.3 | Error:  undefined method `[]' for nil:NilClass
    @level_override[Fiber.current] || @level
                   ^^^^^^^^^^^^^^^
/home/runner/work/matheart.github.io/matheart.github.io/vendor/bundle/ruby/3.1.0/gems/logger-1.6.0/lib/logger.rb:384:in `level': undefined method `[]' for nil:NilClass (NoMethodError)
    @level_override[Fiber.current] || @level
                   ^^^^^^^^^^^^^^^
	from /home/runner/work/matheart.github.io/matheart.github.io/vendor/bundle/ruby/3.1.0/gems/jekyll-3.9.3/lib/jekyll/log_adapter.rb:43:in `adjust_verbosity'
	from /home/runner/work/matheart.github.io/matheart.github.io/vendor/bundle/ruby/3.1.0/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:2[7](https://github.com/Matheart/matheart.github.io/actions/runs/10034328845/job/27728691560#step:5:7):in `process'
	from /home/runner/work/matheart.github.io/matheart.github.io/vendor/bundle/ruby/3.1.0/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /home/runner/work/matheart.github.io/matheart.github.io/vendor/bundle/ruby/3.1.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /home/runner/work/matheart.github.io/matheart.github.io/vendor/bundle/ruby/3.1.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /home/runner/work/matheart.github.io/matheart.github.io/vendor/bundle/ruby/3.1.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /home/runner/work/matheart.github.io/matheart.github.io/vendor/bundle/ruby/3.1.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /home/runner/work/matheart.github.io/matheart.github.io/vendor/bundle/ruby/3.1.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /home/runner/work/matheart.github.io/matheart.github.io/vendor/bundle/ruby/3.1.0/gems/jekyll-3.9.3/exe/jekyll:15:in `<top (required)>'
	from /home/runner/work/matheart.github.io/matheart.github.io/vendor/bundle/ruby/3.1.0/bin/jekyll:25:in `load'
	from /home/runner/work/matheart.github.io/matheart.github.io/vendor/bundle/ruby/3.1.0/bin/jekyll:25:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `load'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/3.1.0/bundler/cli/exec.rb:23:in `run'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/3.1.0/bundler/cli.rb:486:in `exec'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:2[7](https://github.com/Matheart/matheart.github.io/actions/runs/10034328845/job/27728691560#step:5:8):in `run'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:4[8](https://github.com/Matheart/matheart.github.io/actions/runs/10034328845/job/27728691560#step:5:9)5:in `start'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/libexec/bundle:48:in `block in <top (required)>'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/3.1.0/bundler/friendly_errors.rb:[12](https://github.com/Matheart/matheart.github.io/actions/runs/10034328845/job/27728691560#step:5:13)0:in `with_friendly_errors'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/libexec/bundle:36:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/bin/bundle:25:in `load'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/bin/bundle:25:in `<main>'
Error: Process completed with exit code 1.
```

**Comment by Matheart** [comment]
This issue has been fixed after upgrading jekyll to 3.9.5 and github-pages to 231
https://pages.github.com/versions/
