### ISSUE TITLE
Cannot run locally on OSX

### ISSUE THREAD

**Issue by alitk** [academicpages/academicpages.github.io#407]
I followed the procedure mentioned on the Github repo. However, I cannot run in on Mac OSX 10.15.5.  I even tried removing Gemfile.lock, but it did not change anything. `bundle install` works fine but when I try
`bundle exec Jekyll serve` I get the following error:
```zsh
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
bundler: failed to load command: jekyll (/Users/UserName/.gem/ruby/2.6.0/bin/jekyll)
LoadError: dlopen(/Users/UserName/.gem/ruby/2.6.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.bundle, 0x0009): dependent dylib '/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib' not found for '/Users/UserName/.gem/ruby/2.6.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.bundle' - /Users/UserName/.gem/ruby/2.6.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.bundle
  /Users/UserName/.gem/ruby/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:8:in `require'
  /Users/UserName/.gem/ruby/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:8:in `<top (required)>'
  /Users/UserName/.gem/ruby/2.6.0/gems/em-websocket-0.5.1/lib/em-websocket.rb:3:in `require'
  /Users/UserName/.gem/ruby/2.6.0/gems/em-websocket-0.5.1/lib/em-websocket.rb:3:in `<top (required)>'
  /Library/Ruby/Gems/2.6.0/gems/hawkins-2.0.5/lib/hawkins/websockets.rb:2:in `require'
  /Library/Ruby/Gems/2.6.0/gems/hawkins-2.0.5/lib/hawkins/websockets.rb:2:in `<top (required)>'
  /Library/Ruby/Gems/2.6.0/gems/hawkins-2.0.5/lib/hawkins.rb:8:in `require'
  /Library/Ruby/Gems/2.6.0/gems/hawkins-2.0.5/lib/hawkins.rb:8:in `<module:Hawkins>'
  /Library/Ruby/Gems/2.6.0/gems/hawkins-2.0.5/lib/hawkins.rb:3:in `<top (required)>'
  /Users/UserName/.gem/ruby/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `require'
  /Users/UserName/.gem/ruby/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `block (2 levels) in require'
  /Users/UserName/.gem/ruby/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `each'
  /Users/UserName/.gem/ruby/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `block in require'
  /Users/UserName/.gem/ruby/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `each'
  /Users/UserName/.gem/ruby/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `require'
  /Users/UserName/.gem/ruby/2.6.0/gems/bundler-2.1.4/lib/bundler.rb:174:in `require'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-3.8.7/lib/jekyll/plugin_manager.rb:51:in `require_from_bundler'
  /Library/Ruby/Gems/2.6.0/gems/jekyll-3.8.7/exe/jekyll:11:in `<top (required)>'
  /Users/UserName/.gem/ruby/2.6.0/bin/jekyll:23:in `load'
  /Users/UserName/.gem/ruby/2.6.0/bin/jekyll:23:in `<top (required)>'
```
Does anybody have an idea?

**Comment by alitk** [comment]
I tried #117, and it worked for me. Thanks.
