### ISSUE TITLE
Unable to load the EventMachine C extension (on mac)

### ISSUE THREAD

**Issue by raymondchua** [academicpages/academicpages.github.io#889]
Hi, 
I got the following error after running `bundle exec jekyll liveserve`. I am using mac if it helps.

```
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
bundler: failed to load command: jekyll (/Users/raymondchua/.rvm/gems/ruby-3.0.0/bin/jekyll)
/Users/raymondchua/.rvm/gems/ruby-3.0.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:8:in `require': dlopen(/Users/raymondchua/.rvm/gems/ruby-3.0.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.bundle, 0x0009): symbol not found in flat namespace '_SSL_get1_peer_certificate' - /Users/raymondchua/.rvm/gems/ruby-3.0.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.bundle (LoadError)
	from /Users/raymondchua/.rvm/gems/ruby-3.0.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:8:in `<top (required)>'
	from /Users/raymondchua/.rvm/gems/ruby-3.0.0/gems/em-websocket-0.5.3/lib/em-websocket.rb:3:in `require'
	from /Users/raymondchua/.rvm/gems/ruby-3.0.0/gems/em-websocket-0.5.3/lib/em-websocket.rb:3:in `<top (required)>'
	from /Users/raymondchua/.rvm/gems/ruby-3.0.0/gems/hawkins-2.0.5/lib/hawkins/websockets.rb:2:in `require'
	from /Users/raymondchua/.rvm/gems/ruby-3.0.0/gems/hawkins-2.0.5/lib/hawkins/websockets.rb:2:in `<top (required)>'
	from /Users/raymondchua/.rvm/gems/ruby-3.0.0/gems/hawkins-2.0.5/lib/hawkins.rb:8:in `require'
	from /Users/raymondchua/.rvm/gems/ruby-3.0.0/gems/hawkins-2.0.5/lib/hawkins.rb:8:in `<module:Hawkins>'
	from /Users/raymondchua/.rvm/gems/ruby-3.0.0/gems/hawkins-2.0.5/lib/hawkins.rb:3:in `<top (required)>'
	from /Users/raymondchua/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/bundler/runtime.rb:66:in `require'
	from /Users/raymondchua/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/bundler/runtime.rb:66:in `block (2 levels) in require'
	from /Users/raymondchua/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/bundler/runtime.rb:61:in `each'
	from /Users/raymondchua/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/bundler/runtime.rb:61:in `block in require'
	from /Users/raymondchua/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/bundler/runtime.rb:50:in `each'
	from /Users/raymondchua/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/bundler/runtime.rb:50:in `require'
	from /Users/raymondchua/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/bundler.rb:174:in `require'
	from /Users/raymondchua/.rvm/gems/ruby-3.0.0/gems/jekyll-3.9.0/lib/jekyll/plugin_manager.rb:51:in `require_from_bundler'
	from /Users/raymondchua/.rvm/gems/ruby-3.0.0/gems/jekyll-3.9.0/exe/jekyll:11:in `<top (required)>'
	from /Users/raymondchua/.rvm/gems/ruby-3.0.0/bin/jekyll:23:in `load'
	from /Users/raymondchua/.rvm/gems/ruby-3.0.0/bin/jekyll:23:in `<top (required)>'
	from /Users/raymondchua/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `load'
	from /Users/raymondchua/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `kernel_load'
	from /Users/raymondchua/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/bundler/cli/exec.rb:28:in `run'
	from /Users/raymondchua/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/bundler/cli.rb:497:in `exec'
	from /Users/raymondchua/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/raymondchua/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/raymondchua/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/raymondchua/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/bundler/cli.rb:30:in `dispatch'
	from /Users/raymondchua/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/raymondchua/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/bundler/cli.rb:24:in `start'
	from /Users/raymondchua/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/libexec/bundle:49:in `block in <top (required)>'
	from /Users/raymondchua/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	from /Users/raymondchua/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.3/libexec/bundle:37:in `<top (required)>'
	from /Users/raymondchua/.rvm/gems/ruby-3.0.0/bin/bundle:23:in `load'
	from /Users/raymondchua/.rvm/gems/ruby-3.0.0/bin/bundle:23:in `<main>' 
```

**Comment by raymondchua** [comment]
Fixed by following the instructions here: https://github.com/eventmachine/eventmachine/issues/820#issuecomment-964137692
